### ISSUE TITLE
Dependency for source;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [lxqt/lxqt-archiver#128]
I am trying to build from source and cmake cant find fm-qt, is fm-qt pcmanfm-qt?

##### System Information
Distribution & Version: Ubuntu (Lubuntu) 19.04 (Disco Dingo)
Kernel: 5.0.0-31-generic
Qt Version: 0.14.1

**Comment by tsujan** [comment]
> is fm-qt pcmanfm-qt?

libfm-qt is LXQt's file management library.

`lxqt-archiver` builds fine. The problem should be in your system but your report is so uninformative that I can't guess where.

**Comment by Ub3rZ4cH** [comment]
I apologise for not including much info...
I thought that to be the case, as you see in my edit, what info do you need for you to help me build it?

I have both the pcmanfm-qt and libfm-qt installed.

> Note, selecting 'libfm-qt6' instead of 'libfm-qt'
libfm-qt6 is already the newest version (0.14.1-0ubuntu2.1).

Here is the cmake error.

> CMake Error at CMakeLists.txt:31 (find_package):
  By not providing "Findfm-qt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fm-qt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fm-qt" (requested
  version 0.14.0) with any of the following names:

    fm-qtConfig.cmake
    fm-qt-config.cmake

  Add the installation prefix of "fm-qt" to CMAKE_PREFIX_PATH or set
  "fm-qt_DIR" to a directory containing one of the above files.  If "fm-qt"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/jimmy/lxqt-archiver/build/CMakeFiles/CMakeOutput.log".

**Comment by tsujan** [comment]
Most probably, it means that you haven't installed the *dev package* of libfm-qt. Debian based ditros need "dev packages" and RPM based distros need "devel packages" for compilation ("dev" jobs).

**Comment by Ub3rZ4cH** [comment]
Well I would have satified all the dependencies, but since there is no dependencies listed in the readme, or a dependencies.MD It was guess work. I installed the dev package, and had to install `lxqt-build-tools` now I have more issues.

cmake output;
`jimmy@jimmy-pc:~/lxqt-archiver/build$ cmake ..
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.60.4
-- Found GLIB: /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include (found suitable version "2.60.4", minimum required is "2.50.0") 
-- Checking for module 'json-glib-1.0'
--   No package 'json-glib-1.0' found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jimmy/lxqt-archiver/build`

but then I get errors regarding glib again in make;

`[ 28%] Building C object src/core/CMakeFiles/lxqt-archiver-core.dir/fr-command-unarchiver.c.o
/home/jimmy/lxqt-archiver/src/core/fr-command-unarchiver.c:29:10: fatal error: json-glib/json-glib.h: No such file or directory
 #include <json-glib/json-glib.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/core/CMakeFiles/lxqt-archiver-core.dir/build.make:323: src/core/CMakeFiles/lxqt-archiver-core.dir/fr-command-unarchiver.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: src/core/CMakeFiles/lxqt-archiver-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by tsujan** [comment]
> but since there is no dependencies listed in the readme

A source directory doesn't need to contain any distro-specific info.

I'm afraid here isn't a place for distro specific questions. You need to learn how to compile from sources. There are so many articles on the Internet. Also, see https://ubuntuforums.org/

**Comment by Ub3rZ4cH** [comment]
You're very rude. Someone asking for help that's all I am. I just simply won't use your program.

**Comment by tsujan** [comment]
>  Someone asking for help that's all I am.

This is a bug tracker. Google for "bug tracker" to know its meaning.

> I just simply won't use your program.

I'm so unfortunate.
