### ISSUE TITLE
rpm2cpio

### ISSUE THREAD

**Issue by jubalh** [lxqt/lxqt-archiver#156]
Building lxqt-archiver also builds rpm2cpio.
On rpm based distros this binary will be already provided by the `rpm` package AFAIK.

I think in this case we shouldn't install our own build of it but rely on the system version. Probably just adding a flag to not install it will help.

Package maintainers on RPM based distros can then add a build requirement on `rpm` / `/usr/bin/rpm2cpio`.

**Comment by tsujan** [comment]
I think lxqt-archiver should NOT rely on another package for its internal executable `rpm2cpio`, which goes into `/usr/lib/lxqt-archiver` and so, doesn't collide with other packages (also see https://github.com/lxqt/lxqt-archiver/pull/153).

Gnome's file-roller does the same thing (the core of lxqt-archiver is that of file-roller).

**Comment by tsujan** [comment]
I downloaded `file-roller-3.26.2-lp151.3.3.x86_64.rpm` from https://software.opensuse.org/package/file-roller. It has `/usr/lib/file-roller/rpm2cpio`.

Side note: lxqt-archiver couldn't open the above-mentioned RPM package (I opened it with Arqiver). That's a bug, which should be fixed in the next version (probably, 0.1.X). Will look into it later.

**Comment by jubalh** [comment]
> I think lxqt-archiver should NOT rely on another package for its internal executable

I don't think it should generally either. My suggestion was to build it only/or build it not when a certain flag is used. So my suggestion is to introduce a build flag for it.

> which goes into /usr/lib/lxqt-archiver and so, doesn't collide with other packages 

I'm aware that it doesn't collide. That was not my point at all.

> Side note: lxqt-archiver couldn't open the above-mentioned RPM package (I opened it with Arqiver). That's a bug, which should be fixed in the next version (probably, 0.1.X). Will look into it later.

One reason could be that the rpm2cpio is not up to date. In which case distros which have this shipped would benefit from their own version ;) So that's exactly one point why my idea might be good.

Note: Please don't close bugs while they are still under discussion.
I understand your points and I partly agree with them. And I would like to discuss together what we think is the right solution.

So in this case I would like to here @luis-pereira thoughts about the subject.

**Comment by tsujan** [comment]
> Note: Please don't close bugs while they are still under discussion.

I closed it because of an undeniable evidence, namely, file-roller in OpenSUSE itself (read above); otherwise, closing an issue doesn't mean the end of a discussion.

**Comment by jubalh** [comment]
>I closed it because of an undeniable evidence, namely, file-roller in OpenSUSE itself (read above); 

It's not evidence, it just means another program does it this way. Not whether it is right or wrong to do it this way :)

> otherwise, closing an issue doesn't mean the end of a discussion.

Yes you are right! I didn't state this properly :)

**Comment by tsujan** [comment]
I admit my other reason of closing it was a habit: to unclutter bug reports quickly in order to see the important ones (these days, I'm overwhelmed by the number of jobs). Sorry for that!

**Comment by tsujan** [comment]
While fixing https://github.com/lxqt/lxqt-archiver/issues/158, I saw that we depend on the output of *our* `rpm2cpio` in `fr-command-rpm.c`. We cannot guarantee that `rpmextract` (the owner of `/usr/bin/rpm2cpio`) will have the same output.

So, we have a strong reason to provide our own internal executable `rpm2cpio`.

**Comment by jubalh** [comment]
What exactly is rpmextract?

**Comment by tsujan** [comment]
An example of what can provide `/usr/bin/rpm2cpio` in non-RPM systems. The same argument applies to other providers and RPM systems too: output.

**Comment by jubalh** [comment]
Sorry, I don't understand what you mean. No matter what name the package, if it provides `rpm2cpio` them `rpm2cpio` should be the `rpm2cpio` binary. And that should always be the same just in different versions/states, right?
I don't see the point here.

**Comment by tsujan** [comment]
It provides a binary *called* `rpm2cpio` that can do specific things. I'm talking about the output of its command, which we rely on in the code.

**Comment by jubalh** [comment]
So what you are saying is that it provides a different rpm2cpio binary which gives different output than our built in version?

**Comment by tsujan** [comment]
That's possible because we don't change our code but other codes might change.

BTW, our `rpm2cpio` can't open some RPM archives that `bsdtar` (which I use in Arqiver) can. `bsdtar` (provided by `libarchive`) does it independently because I don't have `rpm2cpio`.

We've inherited the core code from engrampa (which took it from file-roller) and made some fixes to it. IMO, it's better to remove `rpm2cpio` and rely on `libarchive` for RPM. But, at least to me, that requires a lot of time; the core code is frightening ;)

**Comment by tsujan** [comment]
Reminder:

`rpm2cpio` will be removed if https://github.com/lxqt/lxqt-archiver/pull/193 is merged. Then, the current issue can be closed too.
