### ISSUE TITLE
Icon file

### ISSUE THREAD

**Issue by jubalh** [lxqt/lxqt-archiver#157]
Currently In our desktop file we have `Icon=application-x-archive`.
The problem is that not all icon themes will provide this. And many distributions use hicolor as their fallback icon theme, which also doesn't provide this.
So one way would be to add a general archiver icon to hicolor, or our own icon to hicolor.

Another way would be to have our own archiver related icon, and ship that in the lxqt-archiver package and rely on this. Then we are not dependand on the icon theme.

To my knowledge `application-x-archive` is provided by:
breeze-icon-theme, oxygen-icon-theme and paper-icon theme.

**Comment by tsujan** [comment]
> The problem is that not all icon themes will provide this

Good point.

**Comment by jubalh** [comment]
It would be awesome if we would have a skilled designer here :-)
But I guess we don't.

So maybe we can just find some freely licensed archiver icon and adapt it a little and ship that.

I guess that's the easiest way of solving this, right?

**Comment by tsujan** [comment]
@jubalh 
I think it can be fixed easily. Unfortunately, there isn't enough time before the next LXQt release but the fix could be in the next point release of LXQt Archiver.

It's very nice to see that good reports come after a new release :)

**Comment by tsujan** [comment]
I checked and saw that `application-x-archive` was indeed missing from some important icon sets.

I can propose the SVG version of this icon from [Plataro](https://github.com/tsujan/Plataro) but I really don't know about license obstacles (and don't want to deal with them):

 
![icon](https://user-images.githubusercontent.com/981076/80292100-ae5e8500-8768-11ea-9047-7ec3ed81f714.png)

**Comment by jubalh** [comment]
I like the icon!
I'm also not sure about license obstacles, but since you are the creator of the icons I dont think we have to fear much :)
I would vote to just add it.

**Comment by tsujan** [comment]
So, let's have an icon!

**Comment by tsujan** [comment]
What about this one?

![lxqt-archiver4](https://user-images.githubusercontent.com/981076/80544442-51600a80-89c6-11ea-8932-c3ec738a11c1.png)

The previous one is 1.3 KiB; this is 5 KiB.

Another version of it:

![lxqt-archiver5](https://user-images.githubusercontent.com/981076/80544767-009ce180-89c7-11ea-9198-8a1c7e0c0a2c.png)

More details:

![lxqt-archiver6](https://user-images.githubusercontent.com/981076/80544874-38a42480-89c7-11ea-855c-93fdfd78d821.png)

**Comment by jubalh** [comment]
Looks awesome! I like both, choose whichever you want :)

**Comment by tsujan** [comment]
Thanks for your opinion! I'll add the last icon today.

**Comment by jubalh** [comment]
I suppose then the .desktop file needs to be adapted to use that icon.

I even think having a new point release would be nice because distributions probably still are on packaging LXQt 0.15.0 and then can do this too and have a nice lxqt-archiver.

**Comment by tsujan** [comment]
> I suppose then the .desktop file needs to be adapted to use that icon.

Yes! I added it to the desktop file, window and About dialog. It'll go into `/usr/share/icons/hicolor/scalable/apps/`. Will make a PR soon.

> I even think having a new point release would be nice

I should make point releases for libfm-qt and pcmanfm-qt (because 2 bugs were found and fixed, one of which was important). Will make a point release for lxqt-archiver alongside them. Let's wait for 2-3 weeks to see if a critical bug is found or not.
