### ISSUE TITLE
Allow opening disk images

### ISSUE THREAD

**Issue by Val6789** [lxqt/lxqt-archiver#171]
7-Zip on Windows allows users to open .img disk images as regular archive files, including FAT and NTFS partitions. This is convenient for users that work often with disk images and would allow LXQt users to easily open disk images without requiring additional software.

I think viewing/extracting disk images is already supported by 7z, so this could be easy to add to lxqt-archiver.

**Comment by tsujan** [comment]
OK, `tar` doesn't support `img` and `7z` can't list the contents of images I have in `/boot`; only `bsdtar` can do it flawlessly but it isn't supported by the core code.

So, it seems that we can't do anything with the current core code. Adding `bsdtar` support is theoretically possible but is beyond my time for now.

I'm open to suggestions. Of course, PRs are welcome too.

**Comment by tsujan** [comment]
Disk images support is here: https://github.com/lxqt/lxqt-archiver/pull/199
