### ISSUE TITLE
Remember last settings

### ISSUE THREAD

**Issue by kellerleicheorig** [lxqt/lxqt-archiver#173]
Hi

is it possible that lxqt-archiver can remember the last settings?

And why isn't the archive deleted beforehand if I want to overwrite it? It is constantly adding new files.

The version of lxqt-archiver is 0.2.0
   LXQt version: 0.15.0
   Qt: 5.15.0
   PCLInuxOS 2020 up to date
  Kernel: 5.7.2

Regards
Daniel

**Comment by tsujan** [comment]
> is it possible that lxqt-archiver can remember the last settings?

Yes. For now, it only remembers its window size and splitter position but more keys could/should be added later.

> And why isn't the archive deleted beforehand if I want to overwrite it?

I think the code doesn't cover overwriting for now (although the file dialog asks about it); will investigate that later.
