### ISSUE TITLE
Duplicated assignment 

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/lxqt-archiver#176]
https://github.com/lxqt/lxqt-archiver/blob/853d9124a3e24f87cf15b6da3493b1bd39401321/src/core/fr-archive.c#L1913-L1915
It is possible that removing one of the repeating assignments is enough. It as also possible, that the author meant to set another field of `xfer_data`. Fields `source_id`, `action` and `uri` are not set, sooo.. I really hope someone more familiar with the code investigates it. Have a nice day!

**Comment by shlyakpavel** [comment]
I have reported https://github.com/mate-desktop/engrampa/issues/400

**Comment by tsujan** [comment]
Ah, sometimes it's hard to put code lines in their context. You're right, it can be anything from a copy-paste mistake to an intentional reassignment. We need to read lots of code lines to be certain.

Let's wait for a reply from engrampa developers. They may read the code for us ;)

**Comment by tsujan** [comment]
A month has passed. Apparently, engrampa developers aren't certain either...

**Comment by shlyakpavel** [comment]
Already merged in GNOME "as is"

**Comment by shlyakpavel** [comment]
Let's wait and see :)
