### ISSUE TITLE
Make the side-pane scrollable horizontally

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-archiver#233]
Currently, the text is elided when there's no space for it and the user needs to move the split-view handle to see it. With some archives, that may not be enough either, as they may contain too many nested folders.

Instead, it's better to add a horizontal scrollbar when needed.

**Comment by stefonarch** [comment]
Works fine:

![schermata-20-16-58](https://user-images.githubusercontent.com/10681413/112762962-bbcc6100-9002-11eb-8c69-e786f9871c1b.png)
