### ISSUE TITLE
DND a folder drops an empty one

### ISSUE THREAD

**Issue by pushqrdx** [lxqt/lxqt-archiver#245]
##### Expected Behavior
According to #87 dropping a folder should be supported

##### Current Behavior
only dropping files, when DND a folder the result dropped folder is empty

##### Steps to Reproduce (for bugs)
1. Drag and drop a folder into anywhere in pcmanfm
2. The dropped folder is empty

##### System Information
* Distribution & Version: Void Linux, latest
* Kernel: 5.11.18_1
* Package version: 0.4.0

**Comment by tsujan** [comment]
Not reproducible. Here, folders are dropped with all their contents. I tested with Qt's `qtbase-everywhere-src`, which has many folders.

**Comment by pushqrdx** [comment]
@tsujan why are you closing the issue before any confirmation, it doesn't happen on your machine but it's for some reason happening here on a fresh void-linux lxqt install and even after system upgrade which has most of the latest versions of archiver and other lxqt desktop

**Comment by tsujan** [comment]
> but it's for some reason happening here

Then, you should provide more info for us to reproduce it. We don't have access to your machine.

**Comment by stefonarch** [comment]
I tested too, dragging a folder with many files to /tmp and hit "copy" or "move" - folder with all  files  is copied.

**Comment by pushqrdx** [comment]
> > but it's for some reason happening here
> 
> Then, you should provide more info for us to reproduce it. We don't have access to your machine.

@tsujan Can you please try with a zip archive, i just noticed that `.tar.xz` extracts folders just fine, zip archives are the ones having this issue

**Comment by tsujan** [comment]
No problem with zip archives either.

If your zip archive is small, please attach it here for me to test it.

**Comment by pushqrdx** [comment]
@tsujan sure, here it is, but it happens with other zip files too
[libgccjit.zip](https://github.com/lxqt/lxqt-archiver/files/6446465/libgccjit.zip)
