### ISSUE TITLE
Decrypt of .7z archive failing

### ISSUE THREAD

**Issue by flexid2000** [lxqt/lxqt-archiver#247]
##### Expected Behavior
Decrypting a password protected .7z archive with an encrypted file list should work as expected.

##### Current Behavior
When trying to decrypt such an archive you're prompted with the error message 'password required' but it is not possible to insert the password. Unpacking fails. (The same archive can be unpacked with arqiver, xarchiver or file-roller.)

##### Steps to Reproduce (for bugs)
1. Create a .7z archive, protect it with a password, check 'encrypt file list'
2. Open the archive with lxqt-archiver
3. No insertion of password possible

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.12.6-arch1-1
* Qt Version: 5.15.2
* libqtxdg Version: 3.7.1-1
* lxqt-build-tools Version: 0.9.0-1
* Package version: 0.4.0-1

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/lxqt-archiver/pull/248

Thanks a lot for reporting the problem!

**Comment by tsujan** [comment]
@flexid2000, reports are closed automatically when their corresponding PRs are merged.
