### ISSUE TITLE
Core dump when creating new archive

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-archiver#29]
Selecting from Menu → File  → New Archiver dumps core when saving. No matter what kind of archive is selected.

##### System Information

* Distribution & Version: Arch Linux up to date, latest master LXQt

**Comment by agaida** [comment]
not reproducible here - please be more verbose - a gdb dump might be helpful

**Comment by agaida** [comment]
not reproducible in arch too

**Comment by stefonarch** [comment]
Don't remember how to use gdb.
* create new → name it test, select from the dropdown an random archive type: crash
* create new → name it test.zip, select from the dropdown *.zip: no crash

**Comment by agaida** [comment]
ah, ok - that should be reproducible

**Comment by arthurzam** [comment]
I had made some research on this issue.

The main error happens in this [line](https://github.com/lxqt/lxqt-archiver/blob/master/src/core/fr-archive.c#L1088). When I create a new archive without an extension for the mime-type `get_mime_type_from_filename` returns NULL and fails later.

The solution is to append the extension per the asked file type. There is a small decision to make which preferred extension we want (for example `.tar.gz` or `.tgz`) to auto append.

**Comment by tsujan** [comment]
@agaida If I'm not wrong, I don't receive email notifications from lxqt-archiver repository. Possible?

**Comment by tsujan** [comment]
Oh, my bad! I hadn't click "Watching" here. It should be OK from now on.

**Comment by tsujan** [comment]
Not reproducible in the way described here (or in any way I tried). If it happen under special circumstances, please provide a step-by-step method to reproduce it.

The problem I see is only that no proper extension is added. lxqt-archiver supposes it should be `gz` when no extension is specified by the user, in which case, if a folder is added, error messages will be shown — but no crash.

**Comment by stefonarch** [comment]
Still reproducable in the same way I described above.

> The problem I see is only that no proper extension is added.

I try to add one of the extensions in the dropdown → it crashes. It works adding it manually in the name field.

**Comment by tsujan** [comment]
> I try to add one of the extensions in the dropdown → it crashes.

At last, I saw it with `tar.xz`. It doesn't crash with `zip`, for example.

**Comment by tsujan** [comment]
The problem is in LXQt file dialog. Although it can be worked around here, it's better to fix it in libfm-qt. I try to fix it in https://github.com/lxqt/libfm-qt/pull/425 because it's about extension handling.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/425. lxqt-archiver, lximage-qt and pcmanfm-qt should be recompiled after applying it.

**Comment by stefonarch** [comment]
Works as expected!

**Comment by tsujan** [comment]
Thanks for testing!

**Comment by tsujan** [comment]
@stefonarch If you use the latest git lxqt-archiver, please report any problem you might encounter before the next release (open separate issues for them)! Feature requests are welcome too but problems have a higher priority.

**Comment by stefonarch** [comment]
Hm, unfortunately I'll be away from my pc, for 2 weeks.
But I've just recompiled (only archiver) and encountered 2 issues.
