### ISSUE TITLE
Current sources FTBFS 

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt-archiver#3]
```
lxqt-archiver/snapshot/src/core/fr-archive.c: In function ‘copy_remote_file’:
lxqt-archiver/snapshot/src/core/fr-archive.c:1246:9: error: format not a string literal and no format arguments [-Werror=format-security]
         error = g_error_new (G_IO_ERROR, G_IO_ERROR_NOT_FOUND, _("Archive not found"));
         ^~~~~
lxqt-archiver/snapshot/src/core/fr-archive.c: In function ‘fr_archive_add’:
lxqt-archiver/snapshot/src/core/fr-archive.c:1579:32: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘gpointer’ {aka ‘void *’} [-Wformat=]
             g_print(" dst_fn: %s\n", new_file_list->data);
                               ~^     ~~~~~~~~~~~~~~~~~~~
                               %p
cc1: some warnings being treated as errors
```

**Comment by PCMan** [comment]
@agaida that's the source code of engrampa. Maybe we can workaround this by adding -Wnoformat?
The g_print() stuff can be deleted later. It's the debug message added by me.

**Comment by agaida** [comment]
i set a hardening none for now

**Comment by jubalh** [comment]
> The g_print() stuff can be deleted later. It's the debug message added by me.

https://github.com/lxqt/lxqt-archiver/pull/49 solves the g_print()

> error = g_error_new (G_IO_ERROR, G_IO_ERROR_NOT_FOUND, _("Archive not found"));

Is nothing to worry about. It just happens because the compiler cannot check the string at compile time. In theory one could attack this if the string would be created at runtime and put in from the user. But in this case it comes from the translations. So as long as we don't let anyone submit malicious translations we are good ;)

I propose to ignore this or add a -format to the build script.

**Comment by jubalh** [comment]
Additional info:

Engrampa has this here: https://github.com/mate-desktop/engrampa/blame/f06c2164fbc7b0e890fd2efdb05c0516f5ad3142/src/fr-archive.c#L1247

And the engrampa package in debian stretch/sid is not patched in any way: https://packages.debian.org/stretch/engrampa

So it seems that there is a way to have it accepted without those strict flags. During review of lxqt-archiver one can point them to this fact that the same code is already in their distribution in another package.

**Comment by tsujan** [comment]
I don't know about these things. lxqt-archiver was compiled without problem from day one here. Is there still an issue?

**Comment by agaida** [comment]
@tsujan - see the "solution" above - as long we don't do our homework the type casts will break the builds with strict compiler settings

**Comment by tsujan** [comment]
@agaida Whenever I compile lxqt-archiver, I see many warnings. So, the code needs a lot of cleanup.

For now, my focus is on usability; there are several problems in that area. But, when the job is finished, I'll take a look into warnings and type casts.

**Comment by agaida** [comment]
there are only two or three typecasts that are critical and not handled - @jubalh's sugesstion might be the way to go for them.

**Comment by tsujan** [comment]
Good.

I think the compiler shows all of them and if not, there are standard ways.

`g_print` can be commented out when lxqt-archiver is proved to be reliable. I think it is so but tests with various kinds of archives are needed.

**Comment by jubalh** [comment]
I think we can close this issue. Since "FTBS" is not the case anymore since PR was merged.
