### ISSUE TITLE
Missing icons due non existing ids in freedesktop specification

### ISSUE THREAD

**Issue by redtide** [lxqt/lxqt-archiver#368]
`archive-insert`, `archive-insert-directory` and `archive-extract` are not part of the freedesktop icon naming specification, so the result is missing icons in the toolbar:

![immagine](https://github.com/lxqt/lxqt-archiver/assets/1171962/95024a28-6937-4247-a109-db66bc686201)

There should be at least some fallback icons, even if not in line with the theme in use,
by using somthing like [QIcon::fromTheme fallback](https://doc.qt.io/qt-5/qicon.html#fromTheme-1).

##### Expected Behavior

See summary.

##### Current Behavior

See summary.

##### Possible Solution

See summary.

##### Steps to Reproduce (for bugs)

See summary.

##### Context

See summary.

##### System Information

still a quite up to date Archlinux distro.

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
> archive-insert, archive-insert-directory and archive-extract are not part of the freedesktop icon naming specification

Which names are? In which documentation does `freedesktop.org` set icon names?

**Comment by redtide** [comment]
[here](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)

**Comment by tsujan** [comment]
> here

If you can choose a fallback for `archive-extract`, please tell us — the other icons could have `insert-object` as fallback.

LXQt recommends an icon set as rich as Oxygen (not necessarily Oxygen itself), most icons being outside the basic list of standard names.

**Comment by redtide** [comment]
I guess that most of non standard icons used in some icon themes comes from GNOME and [KDE](https://techbase.kde.org/Projects/Oxygen/namingSpec/actions#Summary_of_the_suggested_changes_and_additions) namings, so they exists as "non standard extensions".

Do you mean `insert-object` as fallback for the standard ones?
If yes might be useful (instead nothing) for incomplete themes. Though I saw either a custom question mark icon or similar; Oxygen seems to have `image-missing` (so to be added to the fallback ones). Or `dialog-question`.

IMO you can use one of the most used/complete like Oxygen, Breeze or whatever you find the most "sober/neutral" as replacement, I have no much of a preference to suggest any, but I use to include Oxygen ones as fallback in some of my GPL projects.

**Comment by tsujan** [comment]
> Do you mean insert-object as fallback for the standard ones?

As the fallback for both `archive-insert` and `archive-insert-directory`. We can't expect more from a fallback ;)

Don't get me wrong; your report is quite relevant. But I don't know of a sensible fallback for extraction; hence asking you.

> I use to include Oxygen ones as fallback in some of my GPL projects.

I use hard-coded symbolic icons that become black/while according to the background (by using a class derived from `QIconEngine`) and, probably (only in FeatherPad), the system icons as an option.

**Comment by redtide** [comment]
> LXQt recommends an icon set as rich as Oxygen (not necessarily Oxygen itself), most icons being outside the basic list of standard names.

So this mean to suggest people to use some rich though non standard themes to hide the issue of non respecting the standard (though the standard itself is not ideal for most people including me)?

As fallback I mean either custom/self made or from another theme including them all, so breeze or oxygen, not from the same with a standard name.

I know about the monochromatic icons you use: by default I use Arqiver but I haven't set it for all archives, so I saw again the problem and opened this issue.

If you think you can't use some other colored icons as fallback because there are many monochromatic themes out there well, IDK what is best here, I dislike such themes so I use colored ones anyway, but it's a personal choice, and also using another icon in the same theme that sounds near to the one requested (in some theme might look strange, already done this in the past).

**Comment by tsujan** [comment]
> So this mean to suggest people to use some rich though non standard themes

Icon sets aren't nonstandard; they're beyond standard. An icon set that only contains freedesktop's list is good for nothing.

> If you think you can't use some other colored icons as fallback

In LXQt, we only add the app icons, and not hard-coded.

`go-down` may be used as the fallback for extraction.

**Comment by redtide** [comment]
> Icon sets aren't nonstandard; they're beyond standard. An icon set that only contains freedesktop's list is good for nothing.

Call it as you like, beyond/above/extended/whatever, still non standard. Tell them the rest, maybe will change their mind.

> In LXQt, we only add the app icons, and not hard-coded.
> 
> `go-down` may be used as the fallback for extraction.

Can't think to something better than that, the standard gives no help in this case (there is only an emblem for download, not even for upload, nothing else).

**Comment by tsujan** [comment]
> No wait, maybe go-up

It looks acceptable too.

**Comment by redtide** [comment]
PR?

**Comment by tsujan** [comment]
Would be appreciated.

**Comment by redtide** [comment]
What about `document-new` and `folder-new` instead `insert-object`?

**Comment by tsujan** [comment]
No, they would be confusing, because of their well known jobs.

**Comment by tsujan** [comment]
IMO, this doesn't need to be overthought. The point is that sensible fallbacks are better than no icon if the user hasn't installed a rich set yet. So many rich sets exist.

As `freedesktop.org` says, what it proposes is "a minimal list of must have icons", with a guideline for "creating new icons that extend the standardized list…" — i.e., it tells how to make richer sets.

**Comment by redtide** [comment]
One thing if can be interesting: the icon theme I use, which is a modified version of the original `lxde-icon-theme` I did years ago, has an `index.theme` file that specifies, among other things described in the [specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) (note the example code for icon lookup in this page), other icon themes from which it inherits:

```ini
[Icon Theme]
Name=nuoveXT.2.3
Comment=nuoveXT 2.3 Icon Theme
Inherits=nuoveXT-1.6,Tango,gnome,crystalsvg
```
in fact I don't miss any non standard icon in my system, because the missing icons are taken at least from the gnome icon set:
![immagine](https://github.com/lxqt/lxqt-archiver/assets/1171962/cbb6095a-7b97-4270-bd0a-3314a00184c7)

So I wonder if this is some missing feature in Qt to read icons from themes inheriting from other themes, so not completely following the specification but just looking in the filesystem.

This works on Qt Designer:
![immagine](https://github.com/lxqt/lxqt-archiver/assets/1171962/476d1174-e660-47b5-99c3-fa91679d2ee3)

**Comment by tsujan** [comment]
> the missing icons are taken at least from the gnome icon set:

… which is made for GNOME/GTK and lacks many icons some Qt apps may need. That's why an icon set as rich as Oxygen or Breeze is recommended when using a Qt-based DE — or a set with `Inherits=breeze,oxygen,gnome,hicolor` (although `hicolor` is automatically taken into account by LXQt's icon engine).

**Comment by redtide** [comment]
I wanted to make a focus to the point that Qt `QIcon::fromTheme` haven't found existing icons that Qt Designer for example have found.
That icon set is really old and I might consider to replace the crystal icons and others with oxygen at some point but that's not the point of my comment and LXQt icon engine have nothing to do either with it.

**Comment by tsujan** [comment]
If you use LXQt, its icon engine (plugin) is active and makes `QIcon::fromTheme` find what it should. If not, Qt alone does the job, which is elementary and may not support several things (a reason for KDE and LXQt making their richer icon engines based on its private headers).

In general, for a more advanced look, regarding whether icons or styles, Qt needs plugins. Under DEs without Qt plugins, `qt5ct` can be used (but it shouldn't be used with LXQt/KDE).
