### ISSUE TITLE
the icon is cannot show

### ISSUE THREAD

**Issue by newyorkthink** [lxqt/lxqt-archiver#371]
![image](https://github.com/lxqt/lxqt-archiver/assets/87791643/14117180-2faf-44ec-991d-57fcbc14c185)

**Comment by tsujan** [comment]
Your problem can't be related to lxqt-archiver (also → https://github.com/lxqt/lxqt-archiver/commit/8d08dea04205964ae9b61a8926e4fe7e59b4b84d).
