### ISSUE TITLE
Is there an early version which could build against Qt4? (not a bug, but inquiry)

### ISSUE THREAD

**Issue by barracuda156** [lxqt/lxqt-archiver#375]
Qt5 is broken on Darwin PowerPC and early Intel. Qt4 works perfectly fine.
I have just built `qterminal` today and added a fallback version for old systems into Macports.

However, all tags for `lxqt-archiver` ask for Qt5 – but numbering suggests earlier versions might have existed elsewhere, before moving to GitHub.

**Comment by tsujan** [comment]
lxqt-archiver was started when LXQt was based on Qt5; there's no Qt4-based version of it.
