### ISSUE TITLE
[Arch Linux] zip file cannot be opened even if zip is installed

### ISSUE THREAD

**Issue by coldReactive** [lxqt/lxqt-archiver#397]
##### Expected Behavior

The file opens.

##### Current Behavior

![image](https://github.com/lxqt/lxqt-archiver/assets/1313673/e77e23cf-f7af-401a-84e6-a8c06d96f566)

##### Steps to Reproduce (for bugs)

1. Install zip from the repositories in arch linux after installing lxqt-archiver
2. Try to open a zip file.

##### Context

Not applicable.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 6.9.7-arch1-1
* Qt Version: 5.15.14+kde+r141-1 and 6.7.2-1
* libqtxdg Version: Not installed (Not required in the arch repo.)
* lxqt-build-tools Version: Not Installed (Not required in the arch repo.)
* Package version: 1.0.0-1

**Comment by tsujan** [comment]
Not reproducible, with Arch's zip 3.0-11.

**Comment by stefonarch** [comment]
```
 yay -Qo /bin/unzip
/usr/bin/unzip è contenuto in unzip 6.0-21

```

**Comment by coldReactive** [comment]
> ```
>  yay -Qo /bin/unzip
> /usr/bin/unzip è contenuto in unzip 6.0-21
> ```

What's the english command for this?

**Comment by coldReactive** [comment]
> Not reproducible, with Arch's zip 3.0-11.

I was using that version.

I then installed unzip instead via octopi after removing zip, and it now works.

**Comment by tsujan** [comment]
`zip` is for making zip files, `unzip` for opening/extracting them. That's why `zip` alone didn't have an effect.
