### ISSUE TITLE
DnD to extract file(s) sometimes has unclear behavior

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-archiver#399]
##### Expected Behavior
"Copy here" menu displays immediately when drag-and-drop extracting into a folder or Desktop 

##### Current Behavior
If the file(s) are large and trigger the loading bar, no menu appears until the user clicks a location after the loading is complete, rejecting the original DnD

##### Possible Solution
Menu appears immediately, and when the loading bar is in progress an "X" button appears beside it in case the user wants to cancel

##### Steps to Reproduce (for bugs)
1. Open a fresh lxqt-archiver instance
2. DnD a large file from an archive onto the Desktop or a folder
3. No menu appears until loading is complete and then clicking

##### Context
Confusing behavior

##### System Information

 
* Qt Version: 6.7.2
* libqtxdg Version: git latest
* lxqt-build-tools Version: git latest
* Package version: git latest

**Comment by tsujan** [comment]
That's expected when the DND is based on purely Qt methods and doesn't include X11 codes. And it's important not to have X11 codes.

See this PR comment: https://github.com/lxqt/lxqt-archiver/pull/93

**Comment by isf63** [comment]
The progress bar doesn't inform users that the menu is pending and will be displayed upon a click. It took me a while to figure out the method. Puzzling UX on even 16MB files depending on one's computer.

**Comment by tsujan** [comment]
Nothing can be done about it; doing what apps like engrampa do is not an option (→ PR comment).

That menu isn't ours to show. If it exists, it belongs to the receiving app (not all apps show a menu), and there should be something to drop for it to appear, i.e., the file(s) should be extracted first.
