### ISSUE TITLE
src/archiveritem.cpp: reference to local variable ‘results’ returned [-Wreturn-local-addr]

### ISSUE THREAD

**Issue by Chiitoo** [lxqt/lxqt-archiver#41]
##### Expected Behavior
Compiler warning via '-Wreturn-local-addr' probably shouldn't be triggered.

##### Current Behavior
```
src/archiveritem.cpp:82:39: warning: reference to local variable
  ‘results’ returned [-Wreturn-local-addr]
     std::vector<const ArchiverItem *> results;
                                       ^~~~~~~
```

##### Steps to Reproduce (for bugs)
1. Should probably happen during a normal build, in all currently available build configurations?

##### Context
At least on Gentoo, this triggers QA notices like so:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * [...]/work/lxqt-archiver-9999/src/archiveritem.cpp:82:39: warning:
  reference to local variable ‘results’ returned [-Wreturn-local-addr]
```

##### System Information
* Distribution & Version: Gentoo (Chiitoo Edition)
* Kernel: Linux 4.18.8 with Gentoo Patchset
* Qt Version: 5.12.0 (b7a123a6)
* libqtxdg Version: 374f4184
* lxqt-build-tools Version: c2c6539d
* Package version: f03bfe3e

**Comment by tsujan** [comment]
There are lots of compilation warnings here (but the compilation is done correctly). They should be silenced together at some point.

**Comment by shlyakpavel** [comment]
> There are lots of compilation warnings here (but the compilation is done correctly). They should be silenced together at some point.

Imo the one mentioned above makes sense and should be fixed (idk how)

**Comment by tsujan** [comment]
> Imo the one mentioned above makes sense

Yes! I `ArchiverItem::allChildren()` isn't used anywhere, so it causes no problem. It should be removed though.

**Comment by shlyakpavel** [comment]
> Yes! I `ArchiverItem::allChildren()` isn't used anywhere, so it causes no problem. It should be removed though.

It seems to be used now :D

**Comment by tsujan** [comment]
> It seems to be used now :D

`ArchiverItem::allChildren(std::vector<const ArchiverItem*>&)` is sued, but not `ArchiverItem::allChildren()`, to which this issue is related.

**Comment by tsujan** [comment]
No `ArchiverItem::allChildren()` anymore. Closing…
