### ISSUE TITLE
[Arch Linux] `p7zip` package was replaced with `7zip`

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-archiver#411]
`p7zip` was removed in favor of `7zip` due to security vulnerabilities. [Per the discussion](https://gitlab.archlinux.org/archlinux/packaging/packages/p7zip/-/issues/2), 7zip has a few command-line differences to p7zip.

`7-zip-full` is still available in the AUR, and conflicts with `7zip`.

Ubuntu has made p7zip a [transitional package](https://packages.ubuntu.com/search?keywords=7z&searchon=names&suite=oracular&section=all).

----

Testing after upgrading, I am able to navigate 7z archives but unable to add files.

##### System Information

* Distribution & Version: Arch Linux
* Qt Version: 5.15.16+kde+r130-3, 6.8.1-1
* Package version: 1.1.0.r1.gecbb11b-1

**Comment by tsujan** [comment]
We already have the option `USE_7Z`. See https://github.com/lxqt/lxqt-archiver/pull/380

Whether we should set it to `ON` by default, is another question.

**Comment by tsujan** [comment]
The decision has been made by major distros; hence merging https://github.com/lxqt/lxqt-archiver/pull/412.

**Comment by isf63** [comment]
Tested and adding and removing files works again.
