### ISSUE TITLE
Make it part of LXQt

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-archiver#78]
As a forgetful person, I needed this reminder to dedicate some time to lxqt-archiver to get familiar with its Qt code (the C code is too huge), find and fix its (probable) issues, and add features to it.

The goal: Make it an active component of the next release!

**Comment by agaida** [comment]
That would be great - we could release an early alpha - and let our users find bug.

**Comment by tsujan** [comment]
For now, I think that there's no important issue in libfm-qt or pcmanfm-qt, so I give their share of my coding time to lxqt-archiver for a while. It definitely deserves a higher status.

**Comment by tsujan** [comment]
Started. Closing this...
