### ISSUE TITLE
Core dump when saving test.zip without zip installed.

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-archiver#98]
##### Steps to Reproduce (for bugs)

1. Uninstall zip, archiver will not show it in the dropdown list
2. Create an archive named "test.zip"
3. hit "save"
4. it will crash and not save

It should warn about missing zip install instead.

Sorry for the hurry I'm in. 

EDIT: the above  is true for any suffix  - existing or not - you choose, so test.xu test.pq, test.mp3

**Comment by tsujan** [comment]
Thanks! I'll investigate it.

**Comment by tsujan** [comment]
Yes, it also crashes on creating an absurd archive (like `a.blah`).

The code just needs nullity checks. Moreover, the current tree should be cleared on creating an impossible archive. They're easy to fix and implement; will do it after my other PRs are merges, because of conflicts.

**Comment by tsujan** [comment]
BTW, Arqiver adds a suitable supported extension on such occasions; for example, it turns `a.blah` to `a.blah.tar.xz` and really creates the archive. Maybe, that should be added as an option to lxqt-archiver. An idea for future.
